if (!window.PDoc) window.PDoc = {};
PDoc.elements = {
  'Language section': { 'name': 'Language section', 'type': 'section', 'path': '../../language_section.html' },
'Object': { 'name': 'Object', 'type': 'class', 'path': '../../language/object.html' },
'Object.extendAll': { 'name': 'Object.extendAll', 'type': 'class method', 'path': '../../language/object.html#extendall-class_method' },
'String': { 'name': 'String', 'type': 'class', 'path': '../../language/string.html' },
'String#px': { 'name': 'String#px', 'type': 'instance method', 'path': '../../language/string.html#px-instance_method' },
'Number': { 'name': 'Number', 'type': 'class', 'path': '../../language/number.html' },
'Number#px': { 'name': 'Number#px', 'type': 'instance method', 'path': '../../language/number.html#px-instance_method' },
'Prototype section': { 'name': 'Prototype section', 'type': 'section', 'path': '../../prototype_section.html' },
'Prototype.CSSFeatures.PosititionFixed': { 'name': 'Prototype.CSSFeatures.PosititionFixed', 'type': 'class property', 'path': '../../prototype/prototype/cssfeatures.html#posititionfixed-class_property' },
'Event': { 'name': 'Event', 'type': 'class', 'path': '../../prototype/event.html' },
'Event.stopper': { 'name': 'Event.stopper', 'type': 'class method', 'path': '../../prototype/event.html#stopper-class_method' },
'Element': { 'name': 'Element', 'type': 'class', 'path': '../../prototype/element.html' },
'Element.centerInViewport': { 'name': 'Element.centerInViewport', 'type': 'class method', 'path': '../../prototype/element.html#centerinviewport-class_method' },
'Element.setWidth': { 'name': 'Element.setWidth', 'type': 'class method', 'path': '../../prototype/element.html#setwidth-class_method' },
'Element.setHeight': { 'name': 'Element.setHeight', 'type': 'class method', 'path': '../../prototype/element.html#setheight-class_method' },
'Element.setDimensions': { 'name': 'Element.setDimensions', 'type': 'class method', 'path': '../../prototype/element.html#setdimensions-class_method' },
'Tools section': { 'name': 'Tools section', 'type': 'section', 'path': '../../tools_section.html' },
'Stylesheet': { 'name': 'Stylesheet', 'type': 'namespace', 'path': '../../tools/stylesheet.html' },
'Stylesheet.link': { 'name': 'Stylesheet.link', 'type': 'class method', 'path': '../../tools/stylesheet.html#link-class_method' },
'Stylesheet.linked': { 'name': 'Stylesheet.linked', 'type': 'class method', 'path': '../../tools/stylesheet.html#linked-class_method' },
'Stylesheet.findLink': { 'name': 'Stylesheet.findLink', 'type': 'class method', 'path': '../../tools/stylesheet.html#findlink-class_method' },
'Stylesheet.linkTo': { 'name': 'Stylesheet.linkTo', 'type': 'class method', 'path': '../../tools/stylesheet.html#linkto-class_method' },
'Core section': { 'name': 'Core section', 'type': 'section', 'path': '../../core_section.html' },
'Dialog': { 'name': 'Dialog', 'type': 'namespace', 'path': '../../core/dialog.html' },
'Dialog.Options': { 'name': 'Dialog.Options', 'type': 'class property', 'path': '../../core/dialog.html#options-class_property' },
'Dialog.init': { 'name': 'Dialog.init', 'type': 'class method', 'path': '../../core/dialog.html#init-class_method' },
'Dialog.effectsQueue': { 'name': 'Dialog.effectsQueue', 'type': 'class method', 'path': '../../core/dialog.html#effectsqueue-class_method' },
'Dialog.register': { 'name': 'Dialog.register', 'type': 'class method', 'path': '../../core/dialog.html#register-class_method' },
'Dialog.unregister': { 'name': 'Dialog.unregister', 'type': 'class method', 'path': '../../core/dialog.html#unregister-class_method' },
'Dialog.close': { 'name': 'Dialog.close', 'type': 'class method', 'path': '../../core/dialog.html#close-class_method' },
'Dialog.closeAll': { 'name': 'Dialog.closeAll', 'type': 'class method', 'path': '../../core/dialog.html#closeall-class_method' },
'Dialog.log': { 'name': 'Dialog.log', 'type': 'class method', 'path': '../../core/dialog.html#log-class_method' },
'Dialog.Interface': { 'name': 'Dialog.Interface', 'type': 'mixin', 'path': '../../core/dialog/interface.html' },
'Dialog.Interface.getFrame': { 'name': 'Dialog.Interface.getFrame', 'type': 'class method', 'path': '../../core/dialog/interface.html#getframe-class_method' },
'Dialog.Interface.close': { 'name': 'Dialog.Interface.close', 'type': 'class method', 'path': '../../core/dialog/interface.html#close-class_method' },
'Dialog.Interface.isModal': { 'name': 'Dialog.Interface.isModal', 'type': 'class method', 'path': '../../core/dialog/interface.html#ismodal-class_method' },
'Dialog.Options.Buttons': { 'name': 'Dialog.Options.Buttons', 'type': 'class property', 'path': '../../core/dialog/options.html#buttons-class_property' },
'Dialog.ButtonPanel': { 'name': 'Dialog.ButtonPanel', 'type': 'class', 'path': '../../core/dialog/buttonpanel.html' },
'new Dialog.ButtonPanel': { 'name': 'new Dialog.ButtonPanel', 'type': 'constructor', 'path': '../../core/dialog/buttonpanel.html#new-constructor' },
'Dialog.ButtonPanel#addButton': { 'name': 'Dialog.ButtonPanel#addButton', 'type': 'instance method', 'path': '../../core/dialog/buttonpanel.html#addbutton-instance_method' },
'Dialog.Base': { 'name': 'Dialog.Base', 'type': 'class', 'path': '../../core/dialog/base.html' },
'new Dialog.Base': { 'name': 'new Dialog.Base', 'type': 'constructor', 'path': '../../core/dialog/base.html#new-constructor' },
'Dialog.Base#layout': { 'name': 'Dialog.Base#layout', 'type': 'instance method', 'path': '../../core/dialog/base.html#layout-instance_method' },
'Dialog.Base#show': { 'name': 'Dialog.Base#show', 'type': 'instance method', 'path': '../../core/dialog/base.html#show-instance_method' },
'Dialog.Base#hide': { 'name': 'Dialog.Base#hide', 'type': 'instance method', 'path': '../../core/dialog/base.html#hide-instance_method' },
'Dialog.Base#close': { 'name': 'Dialog.Base#close', 'type': 'instance method', 'path': '../../core/dialog/base.html#close-instance_method' },
'Dialog.Base#setContents': { 'name': 'Dialog.Base#setContents', 'type': 'instance method', 'path': '../../core/dialog/base.html#setcontents-instance_method' },
'Dialog.Native': { 'name': 'Dialog.Native', 'type': 'mixin', 'path': '../../core/dialog/native.html' },
'Dialog.Native.alert': { 'name': 'Dialog.Native.alert', 'type': 'class method', 'path': '../../core/dialog/native.html#alert-class_method' },
'Dialog.Native.confirm': { 'name': 'Dialog.Native.confirm', 'type': 'class method', 'path': '../../core/dialog/native.html#confirm-class_method' },
'Dialog.Native.prompt': { 'name': 'Dialog.Native.prompt', 'type': 'class method', 'path': '../../core/dialog/native.html#prompt-class_method' },
'$alert': { 'name': '$alert', 'type': 'utility', 'path': '../../core/dollaralert.html' },
'$confirm': { 'name': '$confirm', 'type': 'utility', 'path': '../../core/dollarconfirm.html' },
'$prompt': { 'name': '$prompt', 'type': 'utility', 'path': '../../core/dollarprompt.html' },
'Dialog.Ajax': { 'name': 'Dialog.Ajax', 'type': 'class', 'path': '../../core/dialog/ajax.html' },
'new Dialog.Ajax': { 'name': 'new Dialog.Ajax', 'type': 'constructor', 'path': '../../core/dialog/ajax.html#new-constructor' }
};